### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The getter 'path' was called on null.

### ISSUE THREAD

**Issue by Aza1535** [regulaforensics/DocumentReader-Flutter#12]
can anyone help to fix this problem?

when Im trying to run this code , Ive got this message :

Running Gradle task 'assembleDebug'...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
W/FlutterActivityAndFragmentDelegate(20300): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Debug service listening on ws://127.0.0.1:57488/oMuk3GucEzc=/ws
Syncing files to device Mi9 Pro 5G...
E/flutter (20300): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(, database preparation failed: com.regula.documentreader.api.errors.DocumentReaderException: Cannot create native wrapper, null, null)
E/flutter (20300): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (20300): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (20300): <asynchronous suspension>
E/flutter (20300): #2      DocumentReader.prepareDatabase (package:flutter_document_reader_api/document_reader.dart:6384:12)
E/flutter (20300): <asynchronous suspension>
E/flutter (20300): #3      _MyAppState.initPlatformState (package:flutter_document_reader_api_example/main.dart:159:11)
E/flutter (20300): <asynchronous suspension>
E/flutter (20300): 
I/z.digid.myverd(20300): ProcessProfilingInfo new_methods=685 is saved saved_to_disk=1 resolve_classes_delay=8000
I/Timeline(20300): Timeline: Activity_launch_request time:712569456
E/flutter (20300): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The getter 'path' was called on null.
E/flutter (20300): Receiver: null
E/flutter (20300): Tried calling: path
E/flutter (20300): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
E/flutter (20300): #1      _MyAppState.getImage (package:flutter_document_reader_api_example/main.dart:24:73)
E/flutter (20300): <asynchronous suspension>
E/flutter (20300): #2      _MyAppState.build.<anonymous closure> (package:flutter_document_reader_api_example/main.dart:372:37)
E/flutter (20300): <asynchronous suspension>
E/flutter (20300): 

![image](https://user-images.githubusercontent.com/92906096/138681095-b10e34d8-5396-45a6-8096-bd34949bceab.png)

![image](https://user-images.githubusercontent.com/92906096/138681204-37cb71a0-e5e8-46f9-bb2e-8195179bc032.png)
I was looking for answers on the Internet, but I can not find a similar error in any way, can you tell me any kind of suggestions?
thanks in advance

**Comment by vyakimchik** [comment]
Hello,

Sorry for keeping you waiting!

The error mentioned means that you are using the versions of API and Core that are incompatible with each other. Could you please tell us the versions you are using if this issue hasn't been resolved yet?
